Repository QualityCore/QualityCore-frontend, pull requests merged in 2025-02, with the labels that each got.

#6 2025.02.12 작업지시서 전체조회 UI
  src/App.js
  src/components/Header.js
  src/components/Sidebar.js
  src/pages/work/WorkOrder.js
  src/pages/work/workOrders.css
Labels: 📓문서 작업📓

#13 25.02.13 작업장 등록 CSS 상단부분 완
  .github/ISSUE_TEMPLATE/error-template.md
  .github/ISSUE_TEMPLATE/to-do-list.md
  package.json
  src/App.js
  src/pages/standard-information/workplace/WorkplaceForm.js
  src/pages/standard-information/workplace/WorkplacePage.js
  src/pages/standard-information/workplace/WorkplaceTable.js
  src/standardinformation/workplace/WorkplaceForm.js
  src/standardinformation/workplace/WorkplacePage.js
  src/styles/workplace-form.css
  src/styles/workplace-table.css
Labels: 도와주십쇼😢

#16 25.02.14 조회 구문 db 불러오기 구현
  package-lock.json
  package.json
  src/App.js
  src/apis/standard-information/WorkplaceApi.js
  src/components/standard-information/WorkplaceForm.js
  src/components/standard-information/WorkplaceList.js
  src/components/standard-information/WorkplaceTable.js
  src/pages/standard-information/WorkplacePage.js
  src/pages/standard-information/workplace/WorkplacePage.js
  src/styles/standard-information/workplace-form.css
  src/styles/standard-information/workplace-table.css
  yarn.lock
Labels: 도와주십쇼😢

#18 25.02.17 작업장정보 등록 구현
  package-lock.json
  package.json
  src/apis/standard-information/WorkplaceApi.js
  src/components/common/Modal.js
  src/components/standard-information/WorkplaceForm.js
  src/components/standard-information/WorkplaceList.js
  src/components/standard-information/WorkplaceTable.js
  src/pages/standard-information/WorkplacePage.js
  src/styles/common/modal.css
  src/styles/standard-information/workplace-form.css
  src/styles/standard-information/workplace-table.css
  yarn.lock
Labels: 도와주십쇼😢

#36 📑 2025-02-19 | 프론트엔드 스케줄표 등록 모달창
  package-lock.json
  package.json
  src/apis/attendanceApi/attendanceApi.js
  src/pages/attendance/Attendance.js
  src/pages/attendance/attendance.module.css
  yarn.lock
Labels: 📓문서 작업📓

#40 📑 2025-02-21 | 직원 스케줄 등록
  package-lock.json
  package.json
  src/apis/attendanceApi/attendanceApi.js
  src/lottie/Success.json
  src/lottie/SuccessNotification.js
  src/lottie/Warning.json
  src/lottie/WarningNotification.js
  src/pages/attendance/Attendance.js
  src/pages/attendance/attendance.module.css
  yarn.lock
Labels: 📌일거리 등록📌

#44 📑 2025-02-21 | 스케줄 상세페이지
  src/apis/attendanceApi/attendanceApi.js
  src/pages/attendance/Attendance.js
  src/pages/attendance/attendance.module.css
Labels: 📌일거리 등록📌

#60 25-02-28 문정현 | 생산계획상세페이지 80%완료
  package-lock.json
  package.json
  src/App.js
  src/apis/productionPlanApi/ProductionPlanApi.js
  src/apis/productionPlanApi/ProductionPlanDetailApi.js
  src/components/productionPlan/PremiumBreweryCalendar.js
  src/components/productionPlan/ProductionPlanDetailAccordion.js
  src/pages/Home.js
  src/pages/productionPlan/ProductionPlan.js
  src/pages/productionPlan/ProductionPlanDetail.js
  src/pages/productionPlan/ProductionPlanDetailPage.js
  src/pages/productionPlan/ProductionPlanStep1.js
  src/pages/productionPlan/ProductionPlanStep2.js
  src/styles/productionPlan/BreweryCalendar.css
  src/styles/productionPlan/ProductionPlanDetail.css
  src/styles/productionPlan/ProductionPlanDetailAccordion.css
  src/styles/productionPlan/ProductionPlanDetailPage.css
  yarn.lock
Labels: 📌일거리 등록📌

#62 25-02-28 문정현 | 생산지시버튼구현하여 상태변경
  package-lock.json
  package.json
  src/App.js
  src/apis/productionPlanApi/ProductionPlanApi.js
  src/apis/productionPlanApi/ProductionPlanDetailApi.js
  src/components/productionPlan/PremiumBreweryCalendar.js
  src/components/productionPlan/ProductionPlanDetailAccordion.js
  src/pages/Home.js
  src/pages/productionPlan/ProductionPlan.js
  src/pages/productionPlan/ProductionPlanDetail.js
  src/pages/productionPlan/ProductionPlanDetailPage.js
  src/pages/productionPlan/ProductionPlanStep1.js
  src/pages/productionPlan/ProductionPlanStep2.js
  src/styles/productionPlan/BreweryCalendar.css
  src/styles/productionPlan/ProductionPlanDetail.css
  src/styles/productionPlan/ProductionPlanDetailAccordion.css
  src/styles/productionPlan/ProductionPlanDetailPage.css
  yarn.lock
Labels: 📌일거리 등록📌

#64 📑 2025-02-21 | 작업지시서 등록 완료
  src/pages/work/WorkCreate.js
  src/pages/work/workCreate.css
Labels: 📌일거리 등록📌
