Repository QualityCore/QualityCore-frontend, pull requests merged in 2025-03, with the labels that each got.

#67 📑 2025-03-03 | 작업지시서 조회
  package-lock.json
  package.json
  src/Pagination/Pagination.js
  src/Pagination/Pagination.module.css
  src/apis/workOrderApi/workOrdersApi.js
  src/common/PDF/generatePDF.js
  src/pages/work/WorkCreate.js
  src/pages/work/WorkOrder.js
  src/pages/work/workCreate.css
  src/pages/work/workCreate.module.css
  src/pages/work/workOrders.module.css
  yarn.lock
Labels: 📌일거리 등록📌

#69 25-03-03 문정현 | Routing 공정현황
  src/apis/routingApi/ProcessTrackingApi.js
  src/components/productionPlan/PremiumBreweryCalendar.js
  src/components/productionPlan/ProductionPlanDetailAccordion.js
  src/pages/productionPlan/ProductionPlan.js
  src/pages/productionPlan/ProductionPlanDetail.js
  src/pages/productionPlan/ProductionPlanDetailPage.js
  src/pages/routing/processTracking.js
  src/styles/productionPlan/BreweryCalendar.css
  src/styles/productionPlan/BreweryCalendar.module.css
  src/styles/productionPlan/ProductionPlan.css
  src/styles/productionPlan/ProductionPlanDetail.css
  src/styles/productionPlan/ProductionPlanDetailAccordion.css
  src/styles/productionPlan/ProductionPlanDetailPage.css
  src/styles/productionPlan/ProductionPlanDetailPage.module.css
  src/styles/routing/ProcessTracking.css
Labels: 📌일거리 등록📌

#72 📑 2025-03-03 | 공정정보관리 CSS
  package-lock.json
  package.json
  public/images/10.png
  public/images/11.png
  public/images/11.webp
  public/images/12.webp
  public/images/13.webp
  public/images/14.webp
  public/images/15.webp
  public/images/16.webp
  public/images/17.webp
  public/images/18.webp
  public/images/19.webp
  public/images/7.png
  public/images/8.png
  src/App.js
  src/components/Header.js
  src/components/Sidebar.js
  src/components/standard-information/ProcessStage.js
  src/components/standard-information/processStage.module.css
  src/pages/standard-information/WorkplacePage.js
  src/pages/work/WorkCreate.js
  yarn.lock
Labels: 📌일거리 등록📌

#73 25-03-04 문정현 | 자재관리 중간머지
  src/App.js
  src/apis/productionPlanApi/MaterialApi.js
  src/components/Header.js
  src/components/Sidebar.js
  src/pages/productionPlan/Material.js
  src/pages/routing/processTracking.js
  src/styles/productionPlan/MaterialManagementPage.module.css
  src/styles/routing/ProcessTracking.css
Labels: 📌일거리 등록📌

#80 📑 2025-03-03 | 설비등록
  package-lock.json
  package.json
  src/App.js
  src/apis/standard-information/EquipmentApi.js
  src/components/Header.js
  src/components/Sidebar.js
  src/components/standard-information/Equipment.module.css
  src/components/standard-information/EquipmentInfo.js
  src/components/standard-information/ProcessStage.js
  src/components/standard-information/processData.json
  src/components/standard-information/processStage.module.css
  src/pages/work/WorkCreate.js
  src/pages/work/workOrders.module.css
  yarn.lock
Labels: 📌일거리 등록📌

#85 25-03-06 메인화면 기본레이아웃 & 생산계획갯수그래프
  package-lock.json
  package.json
  src/components/home/ProductionPlanCard.js
  src/pages/Home.js
  src/styles/Home.module.css
  yarn.lock
Labels: 📌일거리 등록📌

#87 📑 2025-03-07 | 설비등록
  src/apis/standard-information/EquipmentApi.js
  src/components/Header.js
  src/components/Sidebar.js
  src/components/standard-information/EquipmentInfo.js
  src/components/standard-information/ProcessStage.js
  src/pages/work/WorkCreate.js
  src/pages/work/WorkOrder.js
  src/styles/standard-information/Equipment.module.css
  src/styles/standard-information/processStage.module.css
  src/styles/work/workCreate.module.css
  src/styles/work/workOrders.module.css
Labels: 📌일거리 등록📌

#90 25-03-07 문정현 | Login UI
  public/images/login001.png
  public/images/login002.png
  public/images/login003.png
  src/App.js
  src/components/Header.js
  src/components/login/Login.js
  src/styles/Login.module.css
Labels: 📌일거리 등록📌

#91 📑 2025-03-07 | 라벨등록
  package.json
  public/images/1-2.jpg
  src/App.js
  src/apis/standard-information/LabelInfoApi.js
  src/components/standard-information/LabelInfo.js
  src/components/standard-information/images/1-1.png
  src/components/standard-information/images/1.png
  src/components/standard-information/images/2-1.png
  src/components/standard-information/images/2.png
  src/components/standard-information/images/3-1.png
  src/components/standard-information/images/3.png
  src/styles/standard-information/labelInfo.module.css
Labels: 📌일거리 등록📌

#94 25-03-09 문정현 | 생산실적
  package-lock.json
  package.json
  public/images/404.png
  public/images/JO.png
  src/App.js
  src/apis/productionPerformance/productionPerformanceApi.js
  src/components/Header.js
  src/components/Sidebar.js
  src/components/login/Login.js
  src/contexts/AuthContext.js
  src/pages/AccessDenied.js
  src/pages/NotFound.js
  src/pages/productionPerformance/ProductionPerformancePage.js
  src/styles/NotFound.module.css
  src/styles/productionPerformance/ProductionPerformance.module.css
  yarn.lock
Labels: 📌일거리 등록📌

#96 📑 2025-03-07 | 게시판조회
  package-lock.json
  package.json
  src/App.js
  src/Pagination/Pagination.js
  src/apis/attendanceApi/attendanceApi.js
  src/apis/boardApi/BoardApi.js
  src/apis/standard-information/EquipmentApi.js
  src/apis/standard-information/LabelInfoApi.js
  src/common/WebSocket/WebsocketContext.js
  src/common/WebSocket/useWebSocket.js
  src/components/Header.js
  src/components/Sidebar.js
  src/components/standard-information/EquipmentInfo.js
  src/components/standard-information/LabelInfo.js
  src/pages/attendance/Attendance.js
  src/pages/attendance/attendance.module.css
  src/pages/board/Board.js
  src/pages/board/BoardCreate.js
  src/pages/board/BoardDetail.js
  src/pages/standard-information/WorkplacePage.js
  src/pages/work/WorkCreate.js
  src/pages/work/WorkOrder.js
  src/styles/Sidebar.css
  src/styles/board/board.module.css
  src/styles/board/boardCreate.module.css
  src/styles/board/boardDetail.module.css
  src/styles/standard-information/Equipment.module.css
  src/styles/standard-information/labelInfo.module.css
  src/styles/standard-information/processStage.module.css
  src/styles/work/workCreate.module.css
  yarn.lock
Labels: 📌일거리 등록📌

#99 25-03-10 문정현 | 비밀번호찾기 (이메일인증)
  src/App.js
  src/components/login/Login.js
  src/components/login/PasswordReset.js
  src/styles/PasswordReset.module.css
Labels: 📌일거리 등록📌

#102 📑 2025-03-11 | 예외처리
  src/App.js
  src/Pagination/Pagination.js
  src/Pagination/Pagination.module.css
  src/apis/boardApi/BoardApi.js
  src/apis/routingApi/ProcessTrackingApi.js
  src/components/standard-information/EquipmentInfo.js
  src/components/standard-information/LabelInfo.js
  src/pages/Home.js
  src/pages/attendance/Attendance.js
  src/pages/attendance/attendance.module.css
  src/pages/board/Board.js
  src/pages/board/BoardCreate.js
  src/pages/board/BoardDetail.js
  src/pages/board/BoardMain.js
  src/pages/productionPlan/ProductionPlanStep2.js
  src/pages/work/WorkCreate.js
  src/pages/work/WorkOrder.js
  src/styles/board/board.module.css
  src/styles/board/boardCreate.module.css
  src/styles/board/boardDetail.module.css
  src/styles/board/boardMain.module.css
  src/styles/standard-information/Equipment.module.css
  src/styles/standard-information/labelInfo.module.css
  src/styles/standard-information/processStage.module.css
  src/styles/work/workOrders.module.css
Labels: 📌일거리 등록📌

#103 25-03-11 문정현 | 마무리 군데군데 손보는중
  public/images/admin.jpg
  public/images/emp001.jpg
  public/images/plan.jpg
  public/images/work.jpg
  src/Pagination/Pagination.module.css
  src/apis/boardApi/BoardApi.js
  src/apis/workOrderApi/workOrdersApi.js
  src/components/Sidebar.js
  src/components/login/Login.js
  src/pages/attendance/Attendance.js
  src/pages/board/Board.js
  src/pages/board/BoardCreate.js
  src/pages/board/BoardDetail.js
  src/pages/board/BoardMain.js
  src/pages/productionPlan/Material.js
  src/pages/productionPlan/ProductionPlan.js
  src/pages/work/WorkOrder.js
  src/styles/Sidebar.css
  src/styles/board/board.module.css
  src/styles/board/boardCreate.module.css
  src/styles/board/boardDetail.module.css
  src/styles/productionPlan/MaterialManagementPage.module.css
  src/styles/work/workOrders.module.css
Labels: 📌일거리 등록📌

#104 📑 2025-03-11 | 숙성쪽 프론트엔드
  package-lock.json
  src/App.js
  src/apis/production-process/maturation-detail/maturationDetailApi.js
  src/apis/production-process/maturation-detail/maturationTimeLogApi.js
  src/pages/production-process/maturation-detail/MaturationDetail.js
  src/pages/production-process/maturation-detail/MaturationPage.js
  src/styles/production-process/MaturationCss.module.css
  src/styles/production-process/MaturationPage.module.css
Labels: 📌일거리 등록📌

#105 📑 2025-03-12 | 공정쪽 간단작업
  src/App.js
  src/apis/production-process/carbonation-process/carbonationProcessApi.js
  src/apis/production-process/packaging-and-shipment/packagingAndShipmentApi.js
  src/apis/production-process/postMaturation-filtration/PostMaturationApi.js
  src/components/carbonation-process/CarbonationProcessControls.js
  src/components/packaging-and-shipment/PackagingAndShipmentControls.js
  src/components/postMaturation-filtration/PostMaturationFiltrationControls.js
  src/components/standard-information/EquipmentInfo.js
  src/pages/postMaturation-filtration/PostMaturationFiltrationPage.js
  src/pages/production-process/carbonation-process/CarbonationProcessPage.js
  src/pages/production-process/maturation-detail/MaturationContoller.js
  src/pages/production-process/packaging-and-shipment/PackagingAndShipmentPage.js
  src/styles/production-process/CarbonationProcess.module.css
  src/styles/production-process/PackagingAndShipment.module.css
  src/styles/production-process/PostMaturationFiltration.module.css
Labels: 🏗️최적화 작업🚧

#107 25-03-12 문정현 | CSS 전체통일 및 수정
  src/components/production-process/boiling-process/BoilingProcessControls.js
  src/components/production-process/filtration-process/FiltrationProcessControls.js
  src/components/production-process/mashing-process/MashingProcessControls.js
  src/components/standard-information/EquipmentInfo.js
  src/components/standard-information/LabelInfo.js
  src/pages/attendance/attendance.module.css
  src/pages/productionPlan/ProductionPlan.js
  src/pages/productionPlan/ProductionPlanStep3.js
  src/pages/work/WorkCreate.js
  src/styles/production-process/BoilingProcessControls.module.css
  src/styles/production-process/FiltrationProcessControls.module.css
  src/styles/production-process/MashingProcessControls.module.css
  src/styles/productionPerformance/ProductionPerformance.module.css
  src/styles/productionPlan/MaterialManagementPage.module.css
  src/styles/productionPlan/ProductionPlan.css
  src/styles/productionPlan/ProductionPlanStep2.module.css
  src/styles/productionPlan/ProductionPlanStep3.module.css
  src/styles/routing/ProcessTracking.module.css
  src/styles/standard-information/Equipment.module.css
  src/styles/standard-information/labelInfo.module.css
  src/styles/work/workCreate.module.css
  src/styles/work/workOrders.module.css
Labels: 📌일거리 등록📌

#108 📑 2025-03-12 | LocalDateTime 수정
  src/apis/production-process/postMaturation-filtration/PostMaturationApi.js
  src/components/postMaturation-filtration/PostMaturationFiltrationControls.js
  src/components/production-process/filtration-process/FiltrationProcessControls.js
  src/pages/production-process/maturation-detail/MaturationContoller.js
  src/pages/production-process/maturation-detail/MaturationDetail.js
Labels: 🏗️최적화 작업🚧

#109 📑 2025-03-12 | 공정마무리
  src/components/carbonation-process/CarbonationProcessControls.js
  src/components/packaging-and-shipment/PackagingAndShipmentControls.js
  src/components/productionPlan/PremiumBreweryCalendar.js
Labels: 📌일거리 등록📌

#112 25-03-12 문정현 | CSS 통일및 AS작업
  src/components/carbonation-process/CarbonationProcessControls.js
  src/components/postMaturation-filtration/PostMaturationFiltrationControls.js
  src/components/standard-information/WorkplaceForm.js
  src/components/standard-information/WorkplaceTable.js
  src/pages/board/BoardMain.js
  src/pages/routing/WortVolumeChart.js
  src/styles/Sidebar.css
  src/styles/board/board.module.css
  src/styles/board/boardMain.module.css
  src/styles/production-process/BoilingProcessControls.module.css
  src/styles/production-process/CarbonationProcess.module.css
  src/styles/production-process/FiltrationProcessControls.module.css
  src/styles/production-process/MashingProcessControls.module.css
  src/styles/production-process/PackagingAndShipment.module.css
  src/styles/production-process/PostMaturationFiltration.module.css
  src/styles/productionPlan/ProductionPlanStep1.css
  src/styles/routing/WortVolumeChart.module.css
  src/styles/routing/WortVolumePage.module.css
  src/styles/routing/WortVolumeTable.module.css
  src/styles/standard-information/workplace-form.css
  src/styles/standard-information/workplace-table.css
Labels: 📌일거리 등록📌

#115 25-03-12 CSS 통일 및 AS ing..
  src/components/production-process/cooling-process/CoolingProcessControls.js
  src/components/productionPlan/ProductionPlanDetailAccordion.js
  src/components/standard-information/LabelInfo.js
  src/pages/routing/processTracking.js
  src/styles/production-process/CoolingProcessControls.module.css
  src/styles/productionPlan/BreweryCalendar.module.css
  src/styles/productionPlan/ProductionPlanDetailAccordion.css
  src/styles/routing/ProcessTracking.module.css
  src/styles/standard-information/processStage.module.css
Labels: 📌일거리 등록📌

#118 25-03-13 문정현 | 공정 CSS 업그레이드
  src/apis/productionPerformance/productionPerformanceApi.js
  src/components/maturation-process/MaturationControls.js
  src/components/production-process/cooling-process/CoolingProcessControls.js
  src/components/production-process/fermentation-details/FermentationDetailsControls.js
  src/pages/productionPerformance/ProductionPerformancePage.js
  src/styles/production-process/CarbonationProcess.module.css
  src/styles/production-process/CoolingProcessControls.module.css
  src/styles/production-process/FermentationDetailsControls.module.css
  src/styles/production-process/MashingProcessControls.module.css
  src/styles/production-process/MaturationCss.module.css
  src/styles/production-process/PostMaturationFiltration.module.css
Labels: 📌일거리 등록📌

#124 25-03-13 문정현 | CSS 수정
  src/components/production-process/boiling-process/BoilingProcessControls.js
  src/components/production-process/material-grinding/MaterialGrindingForm.js
  src/pages/productionPerformance/ProductionPerformancePage.js
  src/pages/work/BeerPodium.js
  src/pages/work/Chart.css
  src/styles/production-process/BoilingProcessControls.module.css
  src/styles/productionPerformance/ProductionPerformance.module.css
Labels: 📓문서 작업📓

#126 📅[ToDo] 2025/03/14 진짜진짜 마무리
  src/components/packaging-and-shipment/PackagingAndShipmentControls.js
  src/components/standard-information/EquipmentInfo.js
  src/components/standard-information/LabelInfo.js
  src/pages/work/WorkCreate.js
  src/styles/standard-information/Equipment.module.css
  src/styles/standard-information/labelInfo.module.css
  src/styles/work/workOrders.module.css
Labels: 📌일거리 등록📌

#127 2025-03-14 문정현 | 메인 CSS 및 권한 나누기
  src/App.js
  src/components/Sidebar.js
  src/components/login/PasswordReset.js
  src/components/login/ProtectedRoute.js
  src/pages/attendance/Attendance.js
  src/pages/productionPerformance/ProductionPerformancePage.js
  src/pages/work/BeerPodium.js
  src/pages/work/Chart.css
  src/pages/work/WorkMain.js
  src/styles/PasswordReset.module.css
  src/styles/WorkMain.module.css
  src/styles/productionPerformance/ProductionPerformance.module.css
  src/styles/productionPlan/MaterialRequestModal.module.css
Labels: 📌일거리 등록📌

#128 25-03-14 문정현 | 정말 찐막 CSS 수정
  src/components/Header.js
  src/pages/board/BoardMain.js
  src/styles/board/boardMain.module.css
Labels: 📌일거리 등록📌

#129 📅[ToDo] 2025/03/14 진짜진짜진짜 마무리
  src/pages/board/BoardDetail.js
  src/pages/work/Chart.css
  src/pages/work/WorkMain.js
  src/styles/WorkMain.module.css
  src/styles/standard-information/Equipment.module.css
  src/styles/work/workOrders.module.css
Labels: 🏗️최적화 작업🚧

#130 25-03-14 문정현 | 생산실적 그래프 오류 수정
  src/components/Header.js
  src/components/Sidebar.js
  src/pages/productionPerformance/ProductionPerformancePage.js
Labels: 📌일거리 등록📌

#131 25-03-14 문정현 | 로그인세션감지 추가
  src/App.js
  src/components/login/Login.js
  src/components/login/SessionManager.js
  src/components/login/SessionManager.module.css
  src/components/login/SessionWelcomeModal.js
  src/components/login/SessionWelcomeModal.module.css
  src/components/login/apiInterceptor.js
  src/pages/attendance/Attendance.js
Labels: 📌일거리 등록📌

#132 25-03-15 문정현 | 찐찐최종수정
  src/components/Header.js
  src/components/Sidebar.js
  src/components/login/SessionWelcomeModal.js
  src/components/packaging-and-shipment/PackagingAndShipmentControls.js
  src/pages/board/Board.js
  src/pages/board/BoardMain.js
  src/pages/productionPerformance/ProductionPerformancePage.js
  src/pages/routing/WortVolumePage.js
Labels: 📌일거리 등록📌
